import com.basaki.rules.model.Message;

global java.util.List list

rule "Hello World"
    dialect "mvel"
    when
        m:Message(status == Message.Status.HELLO, text : text)
    then
        m.text = m.status.getValue() + " " + m.text;
end

rule "Good Bye"
    dialect "java"
    when
        m:Message(status == Message.Status.GOODBYE, text : text)
    then
        m.setText(m.getStatus().getValue() + " " + m.getText());
end
