import com.basaki.rules.model.State;

declare type State
    @propertyChangeSupport
end

rule Bootstrap
    when
        a : State(name == State.NAME.A, state == State.STATE_TYPE.NOTRUN )
    then
        System.out.println(a.getName() + " finished" );
        a.setState( State.STATE_TYPE.FINISHED );
end


rule "A to B"
    when
        State(name == State.NAME.A, state == State.STATE_TYPE.FINISHED )
        b : State(name == State.NAME.B, state == State.STATE_TYPE.NOTRUN )
    then
        System.out.println(b.getName() + " finished" );
        b.setState( State.STATE_TYPE.FINISHED );
end

rule "B to C"
    when
        State(name == State.NAME.B, state == State.STATE_TYPE.FINISHED )
        c : State(name == State.NAME.C, state == State.STATE_TYPE.NOTRUN )
    then
        System.out.println(c.getName() + " finished" );
        c.setState( State.STATE_TYPE.FINISHED );
end

rule "B to D"
    salience 10
    when
        State(name == State.NAME.B, state == State.STATE_TYPE.FINISHED )
        d : State(name == State.NAME.D, state == State.STATE_TYPE.NOTRUN )
    then
        System.out.println(d.getName() + " finished" );
        d.setState( State.STATE_TYPE.FINISHED );
end
